### ISSUE TITLE
Please define EXE4J_JAVA_HOME

### ISSUE THREAD

**Issue by Kherrisan** [Dokyme/DokymeLex#1]
No JVM could be found on your system.
Please define EXE4J_JAVA_HOME
to point to an installed 32-bit JDK or JRE or download a JRE from www.java.com.
运行exe的时候出现问题，提示找不到jdk，虽然JAVA_HOME和EXE4J_JAVA_HOME都已经的的确确被设置到了系统环境变量中了。

**Comment by Dokyme** [comment]
准备放弃exe4j的打包模式，直接使用可执行jar文件。

**Comment by Kherrisan** [comment]
准备放弃使用exe4j进行打包的方式，采用jar可执行文件运行的方式。
